### ISSUE TITLE
ImportError: cannot import name 'container_abcs' from 'torch._six'

### ISSUE THREAD

**Issue by theaaron123** [OATML/non-parametric-transformers#1]
When using the conda env I get the above error.

Fixed locally by replacing "non-parametric-transformers/npt/utils/batch_utils.py",
line 7:

from torch._six import container_abcs

with

import collections.abc as container_abcs

**Comment by jlko** [comment]
Hey theaaron123,

thanks for the issue and sorry for the late response.
This seems to be related to torch changing its import structure between versions.

Are you using our environment.yml to set up the conda env (and therefore using pytorch version 1.7)?

Best
Jannik

**Comment by jlko** [comment]
Btw, were you using our environment.yml file to set up the conda env?

**Comment by theaaron123** [comment]
Yeah using environment.yml, same with the no gpu version

**Comment by jlko** [comment]
Oh, you're completely right – I forgot to push this snippet (https://github.com/OATML/non-parametric-transformers/commit/e119909b9e091219b21be77a13c287212c09e681).
Now, the code should work across PyTorch versions.

Thanks again for bringing this to our attention!
