### ISSUE TITLE
pytorch_lightning version

### ISSUE THREAD

**Issue by csabapol** [OATML/non-parametric-transformers#3]
Hi @jlko 
great results and repository! Using the provided environment file, I get the following error when running the examples:

_.../non-parametric-transformers/npt/loss.py", line 5, in <module>
    from pytorch_lightning.metrics.functional import auroc as lightning_auroc
ModuleNotFoundError: No module named 'pytorch_lightning.metrics'_

My environment has pytorch lightning 1.6.0, and it seems to me the repository structure had changed, Could you provide the correct version of the package, perhaps update the environment.yml for compatibility?
Thanks!

**Comment by jlko** [comment]
Hi @csabapol,

Thanks for reaching out.

You're right, torchmetrics have changed their interface and the new import should be

`from torchmetrics.functional import auroc as lightning_auroc`.

I'll push an update to the main brunch to fix this.
Let me know if this works for and if there is anything else we can do to help!
